### ISSUE TITLE
关于论文仿真的验证

### ISSUE THREAD

**Issue by liuchongxin** [thoughtfulman/Master_Thesis_WuMan#1]
在plotResult的M文件中，加载了BER_SBLA.mat; 文件，但是在文件列表中貌似没有这个文件吧，另外可以否加其他联系方式咨询该论文中仿真实现呢？

**Comment by thoughtfulman** [comment]
Actually there is a file named "BER_SBLA.mat" in folder "Codes/chapter4/SBLA/". 
By the way, this repository is just for my personal usage. I didn't write documents for others to understand it.
